# fly.toml app configuration file generated for learn-fly-mike on 2024-05-22T19:53:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'learn-fly-mike'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "app_daga"
  destination = "/var/www/html/storage"
  snapshot_retention = 3